version: '3'
services:
  nginx:
    environment:
      USR: ${USR}
    build: requirements/nginx/
    container_name: nginx
    ports:
      - '443:443'
        # depends_on:
        #  - wordpress
    volumes:
      - /home/${USR}/data:/var/www/html
    restart: always
